<?php
namespace App\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * Class of User inhrtited form FOSUserBundle
 * 
 * @ORM\Entity
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="users")
 */
class User extends BaseUser
{
    /**
     * ID of user
     * 
     * @var integer
     * 
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * Name
     *
     * @var string $name
     *
     * @ORM\Column(name="name", type="string", length=20)
     * @Assert\NotBlank(message="Name can't be empty!",groups={"edit"})
     * @Assert\Length(
     *      max = "20",
     *      maxMessage="Name can be max. 20 chars long",groups={"edit"}
     * )
     */
    private $name;

    /**
     * Address
     *
     * @var string $address
     *
     * @ORM\Column(name="address", type="string", length=20)
     * @Assert\NotBlank(message="Address can't be empty!",groups={"edit"})
     * @Assert\Length(
     *      max = "20",
     *      maxMessage="Address can be max. 20 chars long",groups={"edit"}
     * )
     */
    private $address;

    /**
     * City
     *
     * @var string $city
     *
     * @ORM\Column(name="city", type="string", length=20)
     * @Assert\NotBlank(message="City can't be empty!",groups={"edit"})
     * @Assert\Length(
     *      max = "20",
     *      maxMessage="City can be max. 20 chars long",groups={"edit"}
     * )
     */
    private $city;

    /**
     * Country
     *
     * @var string $country
     *
     * @ORM\Column(name="country", type="string", length=20)
     * @Assert\NotBlank(message="Country can't be empty!",groups={"edit"})
     * @Assert\Length(
     *      max = "20",
     *      maxMessage="Country can be max. 20 chars long",groups={"edit"}
     * )
     */
    private $country;
    
    ////////////////////////////////////////////////////////////////////////////
    /**
     * Constructor of inherited class which calls constructor of parent
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getCountry(): ?string
    {
        return $this->country;
    }

    /**
     * @param string $country
     */
    public function setCountry(string $country): void
    {
        $this->country = $country;
    }

    /**
     * @return string
     */
    public function getAddress(): ?string
    {
        return $this->address;
    }

    /**
     * @param string $address
     */
    public function setAddress(string $address): void
    {
        $this->address = $address;
    }

    /**
     * @return string
     */
    public function getCity(): ?string
    {
        return $this->city;
    }

    /**
     * @param string $city
     */
    public function setCity(string $city): void
    {
        $this->city = $city;
    }

    public function setEmail($email) {
        $this->setUsername($email);
        return parent::setEmail($email); // TODO: Change the autogenerated stub
    }

}
